
import javax.swing.*;
import java.awt.*;

class Ace {

	private static JFrame frame;
	private JPanel panel1;
	private Screen display;

	public Ace() {

		display.pixelBuffer[0] = (byte) 0x80;

		//set up the program window frame
		frame = new JFrame("ACE (Another Chip-8 Emulator)");
		frame.getContentPane().add(panel1);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(300, 300);
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);

		start();
	}

	public static void main(String args[]) {

		SwingUtilities.invokeLater(new Runnable() {

			public void run() {

				//Use native look and feel
				try {

					//for linux systems like KDE try to use GTK's looks and feel
					if (System.getProperty("os.name").equals("Linux")) {

						//UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
						UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");

					} else {

						UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
					}

				} catch (Exception e) {

					System.out.println(e);
				}

				//create and show the Swing GUI and create the chip 8 instance
				new Ace();
			}
		});

	}

	public void start() {
		
		byte[] cls = {(byte) 0x00, (byte) 0xe0};
		byte[] setv0 = {(byte) 0x60, (byte) 0x04};
		byte[] setv1 = {(byte) 0x61, (byte) 0x1f};
		byte[] setv2 = {(byte) 0x62, (byte) 0x0f};
		byte[] setI = {(byte) 0xf0, (byte) 0x29};
		byte[] drw = {(byte) 0xd1, (byte) 0x25};
		
		short p = (short) 0xff00;

		Chip8 c8 = new Chip8();		//set up the chip8 emulator instance

		display.setInstance(c8);	//let the display JComponent access the chip8 instance
		
		//c8.runOpcode(cls);
		c8.runOpcode(setv0);
		c8.runOpcode(setv1);
		c8.runOpcode(setv2);
		c8.runOpcode(setI);
		c8.runOpcode(drw);
		c8.loadRom("Fishie.ch8");

	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		display = new Screen();
		display.setBackground(new Color(-13355980));
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		panel1.add(display, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}

}
